### ISSUE TITLE
Matcher includes is not working in expectJsonSnapshot

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#100]
### Discussed in https://github.com/pactumjs/pactum/discussions/98

<div type='discussions-op-text'>

<sup>Originally posted by **captaincc423** December  1, 2021</sup>
I'm trying to get some matchers to work in expectJsonSnapshot and I'm running into a few problems:

1. I'm trying to use a variable variable with a string in an "includes()", e.g. `"id": includes(response.body.id)` and it's not working. It always says it doesn't match.

Am I misusing these matchers?</div>

**Comment by olcortesb** [comment]
Hi, I was reviewing the issue and I have a propose for solution.

- I think it's possible to pass a function to _include_ for get the value of body snapshot. For example `include( (resp) => resp.body.id))`.  So in to _src/models/expect.js_ method [_validateJsonSnapshot(response)](https://github.com/pactumjs/pactum/blob/b8186068312325683c80bd96af67039e5022ce5c/src/models/expect.js#L355)  add new 'if' validating if param of _include_ is a functions, if it is true, load the file json snapshot and evaluate the functions.
And, finally send the result to  _jmv.validate( ... )_ , similar to actual behavior of _include_ for string parameter 


What do you thinks about?

**Comment by ASaiAnudeep** [comment]
The matchers are initially designed to support [contract testing](https://pactumjs.github.io/guides/contract-testing.html). Need to evaluate on how it effects the matching capabilities at flow server if we start supporting callback functions.

**Comment by olcortesb** [comment]
Yes, It's true, is necessary evaluate the impact. 

Another solution could be passing the functions as string in to _include()_, and use _eval()_ o _new Function()()_ for evaluate in to [_validateJsonSnapshot(response)](https://github.com/pactumjs/pactum/blob/b8186068312325683c80bd96af67039e5022ce5c/src/models/expect.js#L355) , for example:

``` javascript
...

"id": includes('return response.body.id')
...
// In _validateJasonSnapshot(response)
// Previews validations of return in string
value = new Function(value)(response)
...
const current_rules = jmv.getMatchingRules(value, '$.body')
```

**Comment by olcortesb** [comment]
I add a draft PR for review the second solutions.  #213

**Comment by olcortesb** [comment]
I close Pull Request , comment in the PR! #213

**Comment by ASaiAnudeep** [comment]
@olcortesb  Thank you for taking time to fix this issue.

The easiest resolution would be making the [strict](https://github.com/pactumjs/pactum/blob/master/src/models/expect.js#L358) comparison configurable while validating json snapshots.

```js
const strict = false;
const errors = jmv.validate(actual, expected, all_rules, '$.body', strict);
```

**Comment by olcortesb** [comment]
> @olcortesb Thank you for taking time to fix this issue.
> 
> The easiest resolution would be making the [strict](https://github.com/pactumjs/pactum/blob/master/src/models/expect.js#L358) comparison configurable while validating json snapshots.
> 
> ```js
> const strict = false;
> const errors = jmv.validate(actual, expected, all_rules, '$.body', strict);
> ```
> 
> User needs to be cautious while disabling strict comparison. May be we can pass the `true/false` as the second or third argument.
> 
> ```js
> expectJsonSnapshot(matchers, strict?);
> expectJsonSnapshot(name, matchers, strict?);
> ```

OK, Interesting, I take your recommendation with [strict](https://github.com/pactumjs/pactum/blob/master/src/models/expect.js#L358) comparison configurable and prepare a Pull Request! thanks

**Comment by ASaiAnudeep** [comment]
This is fixed https://github.com/pactumjs/pactum-matchers/pull/26
