### ISSUE TITLE
Support cache mock interactions

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#105]
**Is your feature request related to a problem? Please describe.**
During component testing, we use `useInteraction` to have expectations on the external calls. Same expectations are applied for multiple specs. Some micro-services will cache the response and that makes component tests to remove the cached response from cache server.

**Describe the solution you'd like**
`useInteraction` supports a new boolean property called `cache` will have the expectation exercised only once in the entire component testing cycle.

**Describe alternatives you've considered**
May be expectations would support the call count to be either `0` or `1`.

**Comment by leelaprasadv** [comment]
Instead of `cache`, Let's implement additional property in interactions object. 
  ```js
  exceptions: {
     checkExercised: true    // default
  }
  ```

-   checkExercised - true : all validations and expects of Interactions as usual.
-   checkExercised - false: expects (exercised & callCount) checks will be skipped and a debug log will be printed.

**Comment by leelaprasadv** [comment]
After discussion implementation has been changed to below:

Instead of having it in the a new property "exceptions"
```js
exceptions: {
   checkExercised: true    // default
}
```
the new property has been moved into existing "expects" of Interaction object and is renamed as `disable`
```js
expects: {
   disable: false    // default
}
```
