### ISSUE TITLE
Different behaviour between withCookies(cookies) and withHeaders('cookie', cookies)

### ISSUE THREAD

**Issue by josepmarixg** [pactumjs/pactum#111]
**Describe the bug**
`withCookies()` method encodes the value before sending it, causing it not to work in some scenarios. `withHeaders('cookie', cookie)` doesn't.

withHeaders:
`    "cookie": "dwsid=M_ZChQR1JiTC3tzkLgdnlqMO8j--MFXD9r-bo-y1boZQnzjkfxiHXeWgPO2LytY9y6h0-Vykz99putNywubh5g=="`

withCookies:
`    "cookie": "dwsid=M_ZChQR1JiTC3tzkLgdnlqMO8j--MFXD9r-bo-y1boZQnzjkfxiHXeWgPO2LytY9y6h0-Vykz99putNywubh5g%3D%3D"`

Mind the `%3D%3D` at the end

**To Reproduce**
1. Run a test sending a cookie value using `withCookies()`
2. Inspect the request being sent

**Expected behavior**
I'm not sure if it should be encoded or not, but definitely, Salesforce Commerce Cloud platform doesn't like that, so maybe it should be configurable. Like I said, the behaviour is different if you use `withHeaders('cookie')`, so it's confusing

**Software (please complete the following information):**
 - OS: macOS 12.0.1
 - NodeJS Version: v14.17.6

**Comment by ASaiAnudeep** [comment]
Thank you for reporting the issue - @josepmarixg 

This has been fixed in version [3.1.3](https://github.com/pactumjs/pactum/releases/tag/v3.1.3)
