### ISSUE TITLE
expectJsonSnapshot() array objects validation

### ISSUE THREAD

**Issue by ElnSorokina** [pactumjs/pactum#113]
ExpectJsonSnapshot() doesn’t seem to validate objects in array. 
I have an expected JSON like this:
```
{
  "components": [
    {
       "product": {
        "dairyProduct": {
          "id": "4f6e821a-ad7e-467d-9e92-3d01544215ff",
          "createdAt": "2022-01-19T23:04:27.009Z",
        },
      }
    }
  ]
}
```

I want to write a snapshot matcher like this:

```
.expectJsonSnapshot({
  "components": [
    {
      "product":
          "dairyProduct": {
            "id": uuid(),
            "createdAt": regex(1, DATA.REGEX.ISO_DATE),
          },
    }
  ],
}).name()

```
And it seems to always pass even if the products are different. E.g., it passes if I receive `$.components[0].product.coffeeProduct ` instead of the expected `$.components[0].product.dairyProduct`

Can you please suggest if I need to use a specific matcher for the array objects? 
  

OS: macOS Monterey 12.0.1
NPM: 8.1.0
Node: v17.0.1
Pactum: 3.0.21

**Comment by ASaiAnudeep** [comment]
Thank you for reporting the issue - @ElnSorokina 

This has been fixed in version [3.1.3](https://github.com/pactumjs/pactum/releases/tag/v3.1.3)
