### ISSUE TITLE
Inspect() method does not work on running multiple test files.

### ISSUE THREAD

**Issue by vinayak-kaladhar** [pactumjs/pactum#118]
inspect() method works only for single test case file

test files: 
test/CreateHCF.js
test/CreateShifts.js
test/AssignShifts.js

Trigger command: mocha test/CreateHCF.js test/CreateShifts.js test/AssignShifts.js - it does not work in this case, request and response are not printed.

Trigger command:mocha test/CreateHCF.js - it works in this case, request and response are printed.

**Comment by vinayak-kaladhar** [comment]
@ASaiAnudeep this would really help for debugging.

**Comment by ASaiAnudeep** [comment]
It is working perfectly fine with me.

```js
// test.1.js
const { spec } = require('pactum');

describe('Post 1', () => {

  it('should get post 1', async () => {
    await spec()
      .get('https://jsonplaceholder.typicode.com/posts/1')
      .expectStatus(200)
      .inspect();
  });

});
```

```js
// test.2.js
const { spec } = require('pactum');

describe('Post 2', () => {

  it('should get post 2', async () => {
    await spec()
      .get('https://jsonplaceholder.typicode.com/posts/2')
      .expectStatus(200)
      .inspect();
  });

});
```

Running tests 

```sh
mocha test.1.js test.2.js
```

It prints both req and res for both the tests.

**Comment by vinayak-kaladhar** [comment]
@ASaiAnudeep am very sorry, had this in my test file settings.setLogLevel('ERROR');
and this was blocking the inspect, thanks for the quick turnaround.
