### ISSUE TITLE
Mock listen on all interface 0.0.0.0

### ISSUE THREAD

**Issue by mghstehr** [pactumjs/pactum#119]
mock server is listen on local host by default 127.0.0.1.
Maybe I have not seen in the doc, how is it possible to listen on all interface 0.0.0.0 ?

Best Regards
Matthias

**Comment by leelaprasadv** [comment]
@mghstehr The mock server in pactumJS by default listens on all interface 0.0.0.0/anywhere since it uses nodejs "[http](https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback)" library under the hood.

```sh
netstat -abn

Active Connections

  Proto  Local Address      Foreign Address               State
  TCP     0.0.0.0:80          0.0.0.0:0                   LISTENING  [nginx.exe]
  TCP     0.0.0.0:3000        0.0.0.0:0                   LISTENING [node.exe]
```
So you will be able to access it via `localhost:3000` or `127.0.0.1:3000`, etc

**Comment by mghstehr** [comment]
Ok, let me explain my  settings more detailed.
If have Pactum mock running on WSL2 listen on port 9000. 
When I try to connect from a docker container to the host with:
` wget host.docker.internal:9000`
I get a connection refuse
`Connecting to host.docker.internal:9000 (192.168.65.2:9000)
wget: can't connect to remote host (192.168.65.2): Connection refused`

When I use npm package mock-http-server  and start a server listining 0.0.0.0:9900.
I'm able to connect it from the docker container:
`wget host.docker.internal:9900
Connecting to host.docker.internal:9900 (192.168.65.2:9900)
saving to 'index.html'
index.html           100% |************************************************************************|    17  0:00:00 ETA
'index.html' saved`

So something is different.. my first idea was that it's not listening on all interfaces?
It would be very nice if I could  connect from the container, like I can do with "mock-http-server".

**Comment by ASaiAnudeep** [comment]
I'm using a mac and able to communicate from a container to a mock server running on the host. Here is the sample code..

```js
const { mock } = require('pactum');
mock.start(9292);
```

```sh
docker -it run alpine /bin/sh

# inside container
apk update
apk add curl

curl host.docker.internal:9292

# output
# Interaction Not Found  (which is the default behaviour of pactum mock server)
```
