### ISSUE TITLE
'await' has not effect on this type of expression

### ISSUE THREAD

**Issue by LordA98** [pactumjs/pactum#123]
Hi,

I'm trying to setup PactumJS with a Hapi project.  I've written one small test test but I'm getting the following Typescript error/suggestion:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/25960574/153249164-b6b50fbf-2a1d-4898-99de-e246e8788b1b.png">

Removing 'await' causes the tests to pass all the time (even when they should fail if I change the expected result).  So, await is clearly required but the linter is suggesting otherwise.

1. Setup project with following dependencies:

```
"dependencies": {
    "@hapi/hapi": "^20.2.1"
  },
  "devDependencies": {
    "@types/chai": "^4.3.0",
    "@types/hapi__hapi": "^20.0.10",
    "@types/mocha": "^9.1.0",
    "@types/node": "^17.0.15",
    "chai": "^4.3.6",
    "mocha": "^9.2.0",
    "nodemon": "^2.0.15",
    "npm-run-all": "^4.1.5",
    "pactum": "^3.1.3",
    "ts-node": "^10.5.0",
    "typescript": "^4.5.5"
  }
```

and following tsconfig:

```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "rootDir": "./src",
    "outDir": "./lib",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
  },
  "exclude": [
    "test"
  ]
}
```

2. Create test file like so:

```
import pactum from 'pactum';

it('should return 200', async () => {
  await pactum.spec()
    .get('http://localhost:4000/')
    .expectStatus(200);
});
```

The await keyword does not throw an error but makes an incorrect suggestion that the await keyword is not required but it definitely is.

**Expected behaviour**
No Typescript suggestion to remove something that is required.

**Software (please complete the following information):**
 - OS: Mac OSX 11.6.1
 - NodeJS Version: 16.14.0

This isn't a massive issue, I'm just worried that I / other devs will remove the await keyword and assume the tests are working as expected.

**Comment by ASaiAnudeep** [comment]
Thanks for reporting the issue - @LordA98. To fix this we need to include `toss` at the end of each test case.

```ts
import pactum from 'pactum';

it('should return 200', async () => {
  await pactum.spec()
    .get('http://localhost:4000/')
    .expectStatus(200)
    .toss();
});
```

**Comment by LordA98** [comment]
Thank you!  That has fixed it.
