### ISSUE TITLE
Typescript GraphQLRequest['variables'] type as string when should be as object

### ISSUE THREAD

**Issue by samuelsantia** [pactumjs/pactum#162]
**Describe the bug**
Trying to define a graphQL interaction in typescript project when I try to pass the variables key as object like I get a Typescript error expecting the type as string.

**To Reproduce**
1. Create a typescript project
2. Try to add interaction from `spec().useInteraction()` or `mock.addInteraction()` or any of the related methods.
3. Define the request `graphQL.variables`as object (like in [tests](https://github.com/pactumjs/pactum/blob/master/test/component/graphQL.spec.js#L589))
4. Typescript throws an error because no overload matchs.

**Expected behavior**
Typescript must work with `graphQL.variables` as Record<string, unknown>.

**Screenshots**
![Captura de pantalla 2022-05-26 a las 12 19 09](https://user-images.githubusercontent.com/891869/170468888-741b27d9-99bf-4288-b620-cd9172b7649a.png)
![Captura de pantalla 2022-05-26 a las 12 21 28](https://user-images.githubusercontent.com/891869/170469316-361b81a5-7367-4c42-b9fd-1e4849d0f0a9.png)

**Software (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - NodeJS Version 16.14.7
 - Typescript Version 4.3.5

**Comment by ASaiAnudeep** [comment]
Found the issue - https://github.com/pactumjs/pactum/blob/master/src/exports/mock.d.ts#L5

Feel free to raise a PR to fix it.

**Comment by samuelsantia** [comment]
I've just sent the pull request. If you see any thing I'll try to review as soon as I can.
Thanks :)
