### ISSUE TITLE
Interaction not exercised error is thrown on using contract testing

### ISSUE THREAD

**Issue by vinayak-kaladhar** [pactumjs/pactum#167]
**Describe the bug**
Interaction not exercised error is thrown on using contract testing

**To Reproduce**

Have two made two endpoints up using mock server calls one for get: /api/inventory-service/products and for post: /api/order-service/orders
However flows are getting recorded in the server and can be witnessed under flows tab, but interaction not exercised error is thrown.

**Expected behavior**
Expected interaction to be listed in the pactumjs flow server

**Screenshots**
<img width="1300" alt="Screenshot 2022-06-07 at 6 48 21 PM" src="https://user-images.githubusercontent.com/96525672/172390259-77418d8a-3e40-4153-ac5c-819a98602b73.png">

<img width="1300" alt="Screenshot 2022-06-07 at 6 48 46 PM" src="https://user-images.githubusercontent.com/96525672/172390324-0a5eda28-ddb0-4184-96d1-afa198dfbc73.png">

**Software (please complete the following information):**
 - OS: MAC
 - NodeJS Version: 16.3.1

**Comment by ASaiAnudeep** [comment]
The error "**Interaction Not Exercised**" happens while using `useInteraction` method in your component testing. You can learn more about the component testing pattern [here](https://pactumjs.github.io/guides/component-testing.html#pattern)

Make sure the interaction added through `useInteraction` is invoked by your application under test. 

#### Common Reasons

- Mock server hasn't received any incoming request.
- Mock server has received an incoming request but was not able to match with the interaction. _Set the log level to `DEBUG` to check logs of mock server for identifying the matching issue._
