### ISSUE TITLE
Date Utils

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#168]
**Is your feature request related to a problem? Please describe.**
It would be great to have a inbuilt date manipulating functions like [momentjs](https://momentjs.com/) or [luxon](https://moment.github.io/luxon)

**Describe the solution you'd like**
```js
const { date } = require('pactum');

date.now();
date.now().add({ days: 2});
date.now().minus({ hours: 2}).format('dd MM yyyy');
```

**Comment by wine-fall** [comment]
In javascript world, I think `dayjs` ([website](https://day.js.org/)) is better, and the size of this library is 2kb after zipping.

As the `momentjs`, it doesn't upgrade for long time, and it suggest  users to use `dayjs` as a replacement.

However, as for me, if I need to format some `Date` structure, I just do `import dayjs from 'dayjs'`.

So, In my opinion, maybe there is no need to implement patcum with some Date library
