### ISSUE TITLE
using colon as part of URL

### ISSUE THREAD

**Issue by AlexeyCL** [pactumjs/pactum#171]
**Describe the bug**
I tried to send a GET request with a URL, which contains a colon and it failed with error 401.
My request looks like
```
 const url=`https://${process.env.API_KEY}:${process.env.API_SECRET}@${process.env.URL}/v2/profiles`;
 spec().get(url)
```
I'm using API_KEY and API_SECRET for the basic authentication, that I provide as part of the URL. 
**Important to notice**, that when I use `axios.get(url);` it works as required.
As workaround, I can use also Pactum, but with some changes:
   ```
 const encode=Buffer.from(`${process.env.API_KEY}:${process.env.API_SECRET}`).toString('base64');
    const baseUrl=`https://${process.env.URL}/v2/profiles`;
    await pactum.spec().withHeaders({
            'Authorization': `Basic ${encode}`,
        })
            .get(baseUrl)
            .expectStatus(200);
    });
```

**Expected behavior**
could you please check the option to use the first command without `basic authorization`

**Software (please complete the following information):**
 - OS: macOS
 - NodeJS Version 14.15.1

**Comment by ASaiAnudeep** [comment]
Tracking it https://github.com/ethanent/phin/issues/77
