### ISSUE TITLE
Capture cookies as res.cookies in stores and returns 

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#174]
**Is your feature request related to a problem? Please describe.**
Capture cookies as `res.cookies` in `stores` and `returns` 

**Describe the solution you'd like**
```js
stores('TOKEN', 'res.cookies.token')
```

**Comment by baabouj** [comment]
@ASaiAnudeep I would love to give it a try. Can I handle this?

**Comment by ASaiAnudeep** [comment]
Yes. Please

**Comment by baabouj** [comment]
Thanks 😊
