### ISSUE TITLE
Use stored data in DataFuncHandler

### ISSUE THREAD

**Issue by tzmgit** [pactumjs/pactum#197]
**Is your feature request related to a problem? Please describe.**
I cannot use stored data from previous request to build data in a dataFuncHandler.
Example:
```js
handler.addDataFuncHandler('UserReport', (ctx) => {
    return {
        user_id: '$S{userId}',
        name: 'report for a user'
    }
});

await spec().get('users').stores('userId', 'users[0].id')
await spec().post('user_reports').withJson({
    user_reports: [
        '$F{UserReport}'
    ]
})
```

**Describe the solution you'd like**
The dataFuncHandler uses the stored userId as value for `user_id`.

**Comment by ASaiAnudeep** [comment]
Hello @tzmgit , I have marked this issue as an enhancement. 

As a work around, use `parse` function inside data-function handler.

```js
const { handler, parse } = require("pactum")

handler.addDataFuncHandler('UserReport', (ctx) => {
    return {
        user_id: parse('$S{userId}'),
        name: 'report for a user'
    }
});
```
