### ISSUE TITLE
Non-Thenable Spec type definition

### ISSUE THREAD

**Issue by rupert-mckay** [pactumjs/pactum#199]
**Describe the bug**
`Spec.d.ts` does not include a definition for the `then` method which the real `Spec` class has in JS.

As a result, static analysis by the lint rule [await-thenable](https://typescript-eslint.io/rules/await-thenable/) yields the following result:

`error  Unexpected 'await' of a non-Promise (non-"Thenable") value  @typescript-eslint/await-thenable`

**To Reproduce**

I have provided a full reproduction repository here: [pactum-non-thenable-repro](https://github.com/rupert-mckay/pactum-non-thenable-repro). You only need to run `npm install` and then `npm run lint` to see the issue.

In brief here however:

```ts
import { spec } from "pactum";

it("should get a response with status code 200", async () => {
  await spec().get("http://httpbin.org/status/200").expectStatus(200);
});
```

The above test will fail the lint rule because we are applying `await` to an expression of a non-thenable type. 

**Expected behavior**
There should be no lint or compilation errors or warnings

**Software (please complete the following information):**
 - OS: macOS Monterey Version 12.4
 - NodeJS Version: v18.0.0

**Additional Details**

I can resolve this issue by modifying the contents of `node_modules/pactum/src/models/Spec.d.ts` to add the following method to the class definition:

```ts
then(onFulfilled?: (value: unknown) => unknown, onRejected?: (reason: unknown) => unknown): Promise<unknown>;
```

Perhaps a more specific type is appropriate, but this was the most minimally compatible definition I could find to use, without digging any deeper into the internals of Pactum.

I can raise a PR for this change if the maintainers approve.

**Comment by ASaiAnudeep** [comment]
This looks like a good workaround for now. To be consistent, let's keep the type as `any`. Please raise a PR.
