### ISSUE TITLE
expectJsonSnapshot not works on windows

### ISSUE THREAD

**Issue by tkminh** [pactumjs/pactum#202]
**Describe the bug**
Cannot find snapshot folder

**To Reproduce**
spec.expectJsonSnapshot(); 

**Expected behavior**
It should save json to snapshot files

**Comment by tkminh** [comment]
Hmm, I use cucumberjs to execute my script and I tried to find but could't see it in my directory.
Can a change the path for snapshot folder from somewhere in the config ?

**Comment by leelaprasadv** [comment]
@tkminh aah, you are using cucumberJS. You can still generate and use the JSON snapshot feature with below setup.

> Make sure you add an appropriate name for the snapshot and await on it
```js
await spec.name("user-1").expectJsonSnapshot()
```

> Example:

For instance, a "Then" step syntax for CucumberJS would look something like this
```js
Then(/^I expect response to match a json snapshot (.*)$/, async function (snapshotName) {
  await spec.name(snapshotName).expectJsonSnapshot()
});
```

A working sample test setup 
![image](https://user-images.githubusercontent.com/47483946/189320141-4d27f6ea-b671-4845-803f-3ca787be3d5a.png)


Also you can change the snapshot directory path as
```js
const pactum = require('pactum');
pactum.settings.setSnapshotDirectoryPath("<path_to_directory>")
```

> Additional references

You can find cucumberjs boilerplate code for pactumjs here: https://github.com/pactumjs/pactum-cucumber-boilerplate

**Comment by tkminh** [comment]
Thanks @leelaprasadv , it works like a charm.
