### ISSUE TITLE
expectJsonSnapshot(name) is not working

### ISSUE THREAD

**Issue by tzmgit** [pactumjs/pactum#207]
**Describe the bug**

It is not working as described in doc: https://pactumjs.github.io/api/assertions/expectJsonSnapshot.html#usage

**To Reproduce**
1. Run Test
```
await spec()
    .get("/users")
    .expectJsonSnapshot("name1");
```
2. See error
```
     AssertionError [ERR_ASSERTION]: Snapshot name is required
      at Expect.fail (node_modules/pactum/src/models/expect.js:444:12)
      at Expect._validateJsonSnapshot (node_modules/pactum/src/models/expect.js:332:14)
      at Expect.validate (node_modules/pactum/src/models/expect.js:64:10)
      at Tosser.validateResponse (node_modules/pactum/src/models/Tosser.js:240:23)
      at Tosser.validate (node_modules/pactum/src/models/Tosser.js:207:18)
      at Tosser.toss (node_modules/pactum/src/models/Tosser.js:44:18)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Expected behavior**

It seems duplicate with `name("name1")`, so maybe `expectJsonSnapshot` should not accept name.

**Screenshots**

**Software (please complete the following information):**
 - OS: [e.g. Windows] MacOS
 - NodeJS Version [e.g. 14] 14
 - Test Runner [e.g mocha] mocha

**Additional context**

**Comment by ASaiAnudeep** [comment]
The feature of accepting json snapshot name in the expectation itself was released in [v3.2.2](https://github.com/pactumjs/pactum/releases/tag/v3.2.2) 

Could you please give it a try in the latest version.

**Comment by tzmgit** [comment]
Hi @ASaiAnudeep , can I ask the purpose of supporting name in this method?

**Comment by ASaiAnudeep** [comment]
1. Less lines of code and having it at the `expect` method is more readable.
 ```js
 await spec()
  .name('first-user')
  .get("/users/1")
  .expectJsonSnapshot();
  
 // vs
 
 await spec()
  .get("/users/1")
  .expectJsonSnapshot('first-user');
 ```
 
 2. To support json snapshot assertion in bdd style.
 
 ```js
 const http = spec();
 http.get('/users/1');
 await http.toss();
 http.response().should.have.jsonSnapshot('first-user');
 ```
