### ISSUE TITLE
Cannot find brotli compressed page

### ISSUE THREAD

**Issue by crystalfp** [pactumjs/pactum#226]
**Describe the bug**
`.get("http://localhost/` cannot find `index.html` compressed with brotli, that is `index.html.br`

**To Reproduce**
1. Create test:
```
		test("Gets the static content", async () => {
			await spec()
				.get("http://localhost/")
				.withHeaders({"content-encoding": "br"})
				.expectStatus(200)
				.toss();
		});
```
2. See error: returned status 404
3. Change .get() to: `.get("http://localhost/index.html.br")`
4. Now the test pass

**Expected behavior**
As the browser find the page, I expect also pactum to find it.

**Software (please complete the following information):**
 - OS: Windows 11
 - NodeJS Version: 18.11.0
 - Test Runner: jest

**Comment by ASaiAnudeep** [comment]
Hello @crystalfp, I'm assuming this happens in browsers as it was officially supported by them - https://en.wikipedia.org/wiki/Brotli

Can you please try the same request in Postman or any similar tool.

**Comment by crystalfp** [comment]
Using Thunder Client in VS Code asking for `GET http://localhost/` returns decoded the content of `index.html.br`.
In the browser works with Chrome and Firefox.
Instead cURL cannot find the file if I do: `curl http://localhost/` but with `curl --compressed http://localhost/` it finds the file and decompress it.

**Comment by crystalfp** [comment]
FYI: the workaround I'm using now is:
```
import decompress from "brotli/decompress";

test("Get the static page", async () => {
	await spec()
		.get("/index.html.br")
		.expectStatus(200)
		.expect((ctx) => {
			const uint8array = decompress(ctx.res.buffer);
			const content = new TextDecoder().decode(uint8array);

			expect(content).toStartWith("<!DOCTYPE html>");
			expect(content).toMatch(/<\/body>\s*<\/html>/);
		})
		.toss();
});
```

**Comment by ASaiAnudeep** [comment]
pactum uses **phin** for making requests which internally uses [centra](https://github.com/ethanent/centra/blob/master/model/CentraRequest.js#L10). It only supports gzip', &'deflate'

**Comment by crystalfp** [comment]
I understand. But the [link](https://github.com/ethanent/centra/blob/master/model/CentraRequest.js#L10) you posted said that centra supports brotli compression:
`const supportedCompressions = ['gzip', 'deflate', 'br']`

Could I turn the support of brotli compression into a feature request?

Thanks!
mario
