### ISSUE TITLE
Incomplete Type Definition of Mock Interaction

### ISSUE THREAD

**Issue by sandrofhhealth** [pactumjs/pactum#228]
**Describe the bug**
I cannot use [`stores` property](https://pactumjs.github.io/guides/mock-server.html#stateful-behavior) when I add an interaction item to the mock server in typescript. I think the reason is that [`Interaction` type definition](https://github.com/pactumjs/pactum/blob/0d9accfc667907ec913a2d35ea420b02214d1263/src/exports/mock.d.ts#L45) is not complete.

**Comment by ASaiAnudeep** [comment]
This feature is released in [v3.2.4](https://github.com/pactumjs/pactum/releases/tag/v3.2.4)
