### ISSUE TITLE
No way to silence ECONNRESET and ECONREFUSED errors

### ISSUE THREAD

**Issue by crystalfp** [pactumjs/pactum#230]
**Describe the bug**
Testing server shutdown and accessing it afterwards gives ECONNRESET and ECONREFUSED errors that cannot be handled or ignored.

**To Reproduce**
1. Run the following test (the server has a POST that shutdown itself. I know the security is a risk, but it is not the point here):
```
		test("Shutdown server", async () => {

			await spec()
				.post("http://localhost/api/server")
				.withJson({op: "quit"})
				// .expectError("ECONNRESET")
				.toss();

			// await sleep(4_000);

			await spec()
				.get("http://localhost/")
				// .expectError("ECONNREFUSED")
				.expect((ctx) => {
					expect(ctx.res.body).toBeUndefined();
				})
				.toss();
		}, 10_000);
```
3. The test succeeded, but shows on console the ECONNRESET and ECONREFUSED errors. Nothing critical, but annoying.
4. If I uncomment the two `expectError()` statements the test fails because the errors are not there.
5. Also uncommenting the sleep statement does not change anything.

**Expected behavior**
I expect the errors be always present and checked by the expect statements.
An alternative is to find a way to ignore them to solve the point 3.

**Software (please complete the following information):**
 - OS: Windows 11
 - NodeJS Version 18.11.0
 - Test Runner jest
 - Pactum version 3.2.3

**Comment by ASaiAnudeep** [comment]
Try `SILENT` log level for that particular test.

```js
await spec()
	.get("http://localhost/")
	.expectError("ECONNREFUSED")
        .useLogLevel('SILENT')
	.toss();
