### ISSUE TITLE
Unable to pass Int value from JSON via $S{id} to .withPathParams, resulting in "Validation failed (numeric string is expected)"

### ISSUE THREAD

**Issue by kunaldas1997** [pactumjs/pactum#232]
In a test, an `ID` is being stored using` .stores` when creating a `POST` request. 
the ID is an Integer. However, when passing to `.withPathParams` using `$S{<variable>}`, it results in `Validation failed (numeric string is expected)`. 
The method in the main code has `ParseIntPipe` active for the value.

**Comment by ASaiAnudeep** [comment]
I'm not sure how to replicate the issue.

I'm able to use data management in path params without any effort.

```js
const { spec, stash } = require("pactum");

stash.addDataMap({
  ID: '232'
})

spec()
  .get('https://httpbin.org/anything/{id}')
  .withPathParams('id', '$M{ID}')
  .inspect()
  .toss()
 ```

**Comment by leelaprasadv** [comment]
@kunaldas1997 can you share a sample code for the above issue?

I was also able to make it work with stores. Below is a sample test.

```js
// test.js
const { spec, stash } = require('pactum');

describe('sample test', () => {
  it('get all list users', async () => {
    await spec()
    .get('https://reqres.in/api/users?page=1')
    .stores('id', 'data[0].id')
    .inspect()
  });

  it('get random user', async () => {
    await spec()
    .get('https://reqres.in/api/users/{id}')
    .withPathParams('id', '$S{id}')
    .inspect()
  });
});

```

**Comment by kunaldas1997** [comment]
`it('should create bookmarks', async () => {
        return pac
          .spec()
          .post('/bookmarks/post')
          .withHeaders({
            Authorization: 'Bearer $S{a_t}'
          })
          .withBody(dto)
          .expectStatus(201)
          .stores('bookmarkId', '[0].id').inspect();

      });`

The above part creates the user, and stores the bookmark.
The following part access the same bookmarkId 

` it('should get bookmark by id', async () => {

        return pac
          .spec()
          .get('/bookmarks/get/{id}')
          .withPathParams('id', '$S{bookmarkId}')
          .withHeaders({ Authorization: 'Bearer $S{a_t}' })
          .expectStatus(200)
          .inspect();

      });`

The part I am testing 

`@Get("get/:id")
    getBookmarkById(@GetUser('id') userId: number, @Param('id', ParseIntPipe) bookmarkId: number) {
        return this.bookService.getBookmarkById(userId, bookmarkId);
    };`

**Comment by kunaldas1997** [comment]
Unable to understand the code block here. Sorry for that.

**Comment by ASaiAnudeep** [comment]
It seems the mentioned url is wrong. Why does it has a `get` in between **bookmarks** and **id**?

```diff
- /bookmarks/get/{id}'
+ /bookmarks/{id}'
```

**Comment by ASaiAnudeep** [comment]
I don't think the issue is w.r.t pactum. If you can provide us a sample reproducible code, we can further investigate the issue.

**Comment by kunaldas1997** [comment]
I have already attached that above.

**Comment by ASaiAnudeep** [comment]
Can you create a repository with sample code in github and share it with us.

**Comment by leelaprasadv** [comment]
@kunaldas1997 One GET standalone controller snippet will not help to troubleshoot. 

This is not an issue with pactumJS but your server side implementation. One things that might be causing this is your order of routes in the controller are incorrect ? (apparently in NestJS routes order matter!)

<details><summary>Click for Sample Implementation to replicate</summary>
<p>

```js
// custom.decorator.ts
  import { createParamDecorator, ExecutionContext } from '@nestjs/common';
  
  export const GetUser = createParamDecorator(
    (data: string, ctx: ExecutionContext) => {
      const request = ctx.switchToHttp().getRequest();
      const user = request.user;
  
      return data ? user?.[data] : user;
    },
  );
```

```js
// app.service.ts
import { Injectable } from '@nestjs/common';

@Injectable()
export class BookService {
  getBookmarkById(userId: number, bookmarkId: number): object {
    return {
      "userId":userId, 
      "bookmarkId": bookmarkId
    };
  }

  createBookmark(): object {
    return [
      {
        "id": "1"
      }
    ];
  }
}
```
```js
// app.controller.js
import { Controller, Get, Post, Param, ParseIntPipe, HttpCode } from '@nestjs/common';
import { BookService } from './app.service';
import { GetUser } from './custom.decorator';

@Controller("bookmarks")
export class AppController {
  constructor(private readonly bookService: BookService) {}

  @Post("post")
  @HttpCode(201)
    createBookmark() {
      return this.bookService.createBookmark();
    };

  @Get("get/:id")
    getBookmarkById(@GetUser('id') userId: number, @Param('id', ParseIntPipe) bookmarkId: number) {
        return this.bookService.getBookmarkById(userId, bookmarkId);
    };

    @Get("get/all")
    getBookmarks() {
        return {"hello": "world"};
    };
}
```
</p>
</details>

<details><summary>Click for Tests</summary>
<p>

```js
const {request, spec } = require('pactum');

request.setBaseUrl("http://localhost:3000")

describe('Bookmarks test', () => {

  let dto = {}

  it('should` create bookmarks', async () => {
    await spec()
      .post('/bookmarks/post')
      .withHeaders({ Authorization: 'Bearer $S{a_t}' })
      .withBody(dto)
      .expectStatus(201)
      .stores('bookmarkId', '[0].id').inspect();
  });

  it('should get bookmark by id', async () => {
    await spec()
      .get('/bookmarks/get/{id}')
      .withPathParams('id', '$S{bookmarkId}')
      .withHeaders({ Authorization: 'Bearer $S{a_t}' })
      .expectStatus(200)
      .inspect();
  });

  it('should get bookmark all', async () => {
    await spec()
      .get('/bookmarks/get/all')
      .withHeaders({ Authorization: 'Bearer $S{a_t}' })
      .expectStatus(200)
      .inspect();
  });

});
```
</p>
</details>

#### Swapping the order of `@Get` routes in the above mentioned example implementation gets rid of the error and tests pass.

### References
Below stackoverflow answers should help
* https://stackoverflow.com/a/70088559
* https://stackoverflow.com/questions/59118081/nestjs-validation-failed-numeric-string-is-expected-inside-controllers-nested
