### ISSUE TITLE
Not able to update snapshot directory 

### ISSUE THREAD

**Issue by SVaid6293** [pactumjs/pactum#262]
**Describe the bug**
Not able to update snapshot path and see snapshots

Can you please tell how it can be resolved..

**Comment by leelaprasadv** [comment]
@SVaid6293 Hello!
Can you help share a working sample code that is not working for you? 

Also for snapshots to properly work, you would need to have the spec named as shown in the example in the docs

For assertions
https://pactumjs.github.io/api/assertions/expectJsonSnapshot.html

> A snapshot needs a unique name & it can be defined through spec().name("<unique name>") or expectJsonSnapshot("<name>")


To update snapshot
https://pactumjs.github.io/api/assertions/updateSnapshot.html

**Comment by SVaid6293** [comment]
Hello
I am referring the doc but not able to see the snapshots ..

**Comment by leelaprasadv** [comment]
Can you share more details about your test setup and steps to reproduce the issue?

1. A working example code.
2. Which test runner is being used.
3. Operating System.


A similar case, if you are running with CucumberJS runner please refer to this thread https://github.com/pactumjs/pactum/issues/202

**Comment by SVaid6293** [comment]
I am using like this it('Comparing Json Values', async () => {
  await spec()
  .name('Get-Users-Test')
  .get(c.endpoint2)
  .expectStatus(c.expectedStatusCode).useLogLevel("DEBUG")
 // .expectJson(myResponse.expVal2)
  .expectJsonSnapshot;

});

**Comment by SVaid6293** [comment]
Whole code

import { expect } from "chai"
import { Console } from "console";
import { spec, request,settings } from 'pactum';
import { MyParameters } from "./Params";
import * as fs from 'fs';
import * as myResponse from "./responses.json"


settings.setSnapshotDirectoryPath(__dirname+'\\pactum\\snapshots');
var c=new MyParameters;
request.setBaseUrl(c.baserUrl2);



describe('API tests', () => {
it('Comparing Json Values', async () => {
  await spec()
  .name('Get-Users-Test')
  .get(c.endpoint2)
  .expectStatus(c.expectedStatusCode).useLogLevel("DEBUG")
 // .expectJson(myResponse.expVal2)
  .expectJsonSnapshot;

});

it('Comparing Json Values', async () => {
  await spec()
  .name('Get Users2')
  .get(c.endpoint2)
  .expectStatus(c.expectedStatusCode)
 // .expectJson(myResponse.expVal2)
  .expectJsonSnapshot;

});


})

**Comment by ASaiAnudeep** [comment]
you need to invoke the `expectJsonSnapshot()` method.

```js
it('Comparing Json Values', async () => {
  await spec()
  .name('Get Users2')
  .get(c.endpoint2)
  .expectStatus(c.expectedStatusCode)
  .expectJsonSnapshot();
});
```

**Comment by SVaid6293** [comment]
It worked.Thanks lot
