### ISSUE TITLE
withBearerToken is not found in type definitions

### ISSUE THREAD

**Issue by unickq** [pactumjs/pactum#265]
![image](https://user-images.githubusercontent.com/6696821/225986164-51faa88d-6673-4c47-8739-a036c31260b4.png)

```js
import { spec } from "pactum";

it(`test`, async () => {
  await spec().get("/api/users").withBearerToken("token").expectStatus(200);
});
```

`node_modules/pactum/src/models/Spec.d.ts` doesn't have `withBearerToken`

```
"pactum": "^3.3.2",
"typescript": "^4.9.5"
"jest": "^29.5.0",
```

Do I do something wrong?

**Comment by ASaiAnudeep** [comment]
Try removing the node_modules folder and re-install npm packages. I can see the definition here - https://github.com/pactumjs/pactum/blob/master/src/models/Spec.d.ts#L208

**Comment by unickq** [comment]
Removed, reinstalled

![image](https://user-images.githubusercontent.com/6696821/226146036-1d8ca5a6-3589-436f-9cd0-032fa8532cf9.png)

**Comment by unickq** [comment]
tried `npm install --save-dev pactum` in new project, the same issue. 
Maybe 3.3.2 doesn't have it published
![image](https://user-images.githubusercontent.com/6696821/226146155-21661bea-610a-45e2-bd25-d96d2e014441.png)

**Comment by ASaiAnudeep** [comment]
My bad, the changes are not yet released. Will release the new changes this weekend.

**Comment by pelumisamuel** [comment]
Hi, I have the same issues. The changes are yet to be released, right?
