### ISSUE TITLE
Can't resolve 'fs' while running the test

### ISSUE THREAD

**Issue by mcoulont** [pactumjs/pactum#268]
**Describe the bug**
`./node_modules/pactum/src/models/Spec.js:5:11-24 - Error: Module not found: Error: Can't resolve 'fs'`

**To Reproduce**
1. Run `ng test`
2. See error

**Expected behavior**
The test runs

**Screenshots**

**Software (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - NodeJS Version 18.13.0
 - Test Runner Jasmine/Karma

**Additional context**
pactum uses the fs package, but it seems to have been removed because it contained malicious code : see [this page](https://www.npmjs.com/package/fs?activeTab=readme)

**Comment by ASaiAnudeep** [comment]
The [fs](https://nodejs.org/api/fs.html) module is part of node.js ecosystem. Need to test it's availability in v18.13.0

**Comment by mcoulont** [comment]
In fact, Angular doesn't support 'fs': see [comment on Jul 19, 2018](https://github.com/angular/angular-cli/issues/10681)
