### ISSUE TITLE
TypeScript definition for InteractionDetails model doesn’t include all properties

### ISSUE THREAD

**Issue by ca057** [pactumjs/pactum#270]
**Describe the bug**
The TypeScript definition for the model `InteractionDetails` doesn’t include all properties. I’m happy to add them to the model if the missing properties are expected to be part of the model and shouldn’t only be used internally. For my current project I’m especially interested in the `calls` property.

**To Reproduce**

Run the following test code:

```typescript
const id = await mock.addInteraction({ /* interaction details */ })
const interactionDetails = await mock.getInteraction(id)

interactionDetails.calls // throws a TS error
```

**Expected behavior**
The TypeScript definition should include all (relevant) properties (see redacted example from my test):

```
    {
      "callCount": 1,
      "exercised": true,
      "calls": [
        {
          "request": {
            "method": "POST",
            "path": "",
            "query": {},
            "headers": {
// headers
            },
            "body": {
// body
            }
          },
          "exercisedAt": ""
        }
      ],
      "id": "hauxn",
      "strict": true,
      "request": {
        "matchingRules": {
// matching ruls
        },
        "method": "POST",
        "path": "",
        "queryParams": {},
        "body": {
// body
        }
      },
      "response": {
        "matchingRules": {
// matching rules
        },
        "status": 200,
        "body": {
// shape of body
        }
      },
      "expects": {
        "disable": false,
        "exercised": true
      }
    }
```

Currently, only the following are present:

```typescript
export interface InteractionDetails {
  id: string;
  exercised: boolean;
  callCount: number;
}
```

**Screenshots**
N/A

**Software (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJS Version: v18
 - Test Runner: Jest
 - pactum@3.3.2

**Additional context**
N/A

**Comment by ca057** [comment]
Thanks for addressing this issue so fast! 🤩 

I’m wondering if we could change the TS definition slightly, as the current definitions make it more difficult to use, as I want to search in my test if a specific call was made by checking if a body property matches the right value:

```typescript
// throws a TS error, as `prop` doesn’t exist on type object
expect(interaction.calls?.find((call) => call?.request?.body?.prop === expectedPropValue)).toBeTruthy();
```

If we change the TS definition to the following, it works as expected (properties are known, but I have to ensure the type then myself):

```typescript
export interface InteractionCallRequest {
  method?: string;
  path?: string;
  query?: { [key: string]: unknown };
  headers?: { [key: string]: unknown };
  body?: { [key: string]: unknown };
}
```

Happy to do those changes :)

**Comment by ASaiAnudeep** [comment]
Please raise a PR with the intended changes. Please remember `body` can be a `string`.
