### ISSUE TITLE
spec().stores() may support a custom function

### ISSUE THREAD

**Issue by wine-fall** [pactumjs/pactum#274]
- **Is your feature request related to a problem? Please describe.**
I just feel the using of  `spec().stores()` is too *black box* for me because the args passed to it are all `string` type and I don't know how does it work.

- **Describe the solution you'd like**
May be a `stores()` with custom function passed is better. eg:
```javascript
spec()
.stores((req, res) => {
   return {
      sth,
   };
})
```

- **Describe alternatives you've considered**
 I read the doc and find there is a solution which is `pactum.handler.addCaptureHandler`. However, I just think it's not convenient and I have to use `stores()` and pass two string to it too.

- **Additional context**
I just create a pr and if you guys agree it to be merged, I'm going to add some words to the doc.

**Comment by wine-fall** [comment]
By the way, to be honest, there are lots of types of `pactum` is so confusing. eg:
```typescript
withHeaders(headers: object): Spec;
```
something like this may be better:
```typescript
withHeaders<T>(headers: T): Spec;
```

**Comment by ASaiAnudeep** [comment]
You can create a different issue to track the type definition changes.

**Comment by wine-fall** [comment]
hi @ASaiAnudeep: 

thanks for merging my code! I just update the doc and types of stores, please check.

As for the optimization of other types, I think translate the whole things to typescript is a better choice. And if you'd like to do it in future, I'm happy to join it.

Anyway, I will update some types of pactumjs when I using it and create another issue to track it.
