### ISSUE TITLE
Support for setting agent / proxy on a request

### ISSUE THREAD

**Issue by AlexSicoe** [pactumjs/pactum#283]
**Is your feature request related to a problem? Please describe.**
I need to pass through a corporate proxy. To do this, I need the ability to set an agent to a request/spec

**Describe the solution you'd like**
- Something like a 
```javascript
spec().setAgent(agent)
```
- or set the proxy link directly, and behind the scenes use proxy-agent 
```javascript
spec().setProxy('http://my-proxy.com')
```

**Describe alternatives you've considered**
Currently for the test where I need to pass through the proxy I'm using Axios and setting an agent:

```javascript
const axios = require('axios');
const ProxyAgent = require('proxy-agent');
const expect = require('chai').expect;

// HTTP/HTTPS proxy to connect to
const proxy = process.env.http_proxy || 'http://my-proxy.com';

// Create an instance of the `ProxyAgent` class with the proxy server information
const agent = new ProxyAgent(proxy);

// Create an instance of the `axios` class with the `agent` option set to the instance of `ProxyAgent`
const client = axios.create({ httpsAgent: agent });

describe('Axios test', function() {
  it('should make a request through a proxy', async function() {
    const response = await client.get('https://www.example.com');
    console.log(response.data);
    expect(response.data).to.exist;
  });
});
```

**Things to consider**
To properly test this feature you might need a mock proxy where:
- a client without an agent always receives HTTP **403 Forbidden**
- a client with an agent set to the correct proxy receives HTTP **200**

**Comment by ASaiAnudeep** [comment]
Hello @AlexSicoe , can you please try [withcore](https://pactumjs.github.io/api/requests/withCore.html) to setup a custom agent.

**Comment by AlexSicoe** [comment]
Hi @ASaiAnudeep 

I suppose .withCore() passes options to node's http module, right?

I was able to use proxy like this:

```javascript
const { spec } = require('pactum');
const ProxyAgent = require('proxy-agent');

it('should make a request through a proxy', async function() {
  await spec()
    .get('http://example.com')
    .withCore({ agent: new ProxyAgent('http://www.corporate-proxy.com') })
    .expectStatus(200);
});
```

Thanks a lot!
