### ISSUE TITLE
expectCookiesLike Fails when cookies are set via `setHeaders('Set-Cookie', cookieArray)`

### ISSUE THREAD

**Issue by jmcdo29** [pactumjs/pactum#287]
**Describe the bug**

When multiple cookies are set via the `res.setHeader('Set-Cookie', [cookie1, cookie2, ...cookieN])` format, [as described in the node docs](https://nodejs.org/dist/latest-v18.x/docs/api/http.html#responsesetheadername-value), [`lightcookie`]() incorrectly parses the cookies that come in the response, even though a browser will proper interpret them.

**To Reproduce**

1. Clone [this repo](https://github.com/jmcdo29/pactum-cookie-parsing).
2. Run `pnpm install`
3. Run `pnpm test`
4. Notice the assertion error for the `GET /two-cookies` route

I kept the reproduction as barebones as possible using just pactum and express. 

**Expected behavior**
Honestly, I'd say this should be something for `lightcookie` to fix in its parsing, but seeing as the project hasn't been touched since 2017, I figured this would be a better place to patch around it.

**Screenshots**

**Software (please complete the following information):**
 - OS: [Linux]
 - NodeJS Version [e.g. 20]
 - Test Runner [N/A]

**Additional context**

**Comment by leelaprasadv** [comment]
@tomo324 Feel free to open a PR with the fix, we will be happy to review.
