### ISSUE TITLE
Observed vulnerability while installing pactum via npm

### ISSUE THREAD

**Issue by dimpyadhikary** [pactumjs/pactum#292]
**Describe the bug**
Observed vulnerability while installing pactum via npm

**To Reproduce**
1. npm install -g pactum

**Expected behavior**
There should not be any vulnerability listed.

**Actual behavior**
88 vulnerabilities (38 moderate, 24 high, 26 critical)

**Software (please complete the following information):**
 - Mac book
 -  npm --versions -9.5.1
 - T node --version v18.16.1

**Comment by cbruchwaldnetfonds** [comment]
Hi, we have 0 issues with pactum 3.3.3.
Can you please check with `npm audit` what packages cause this issues?

**Comment by dimpyadhikary** [comment]
Its my bad the vulnerabilities were from other packages. I just confirmed with the npm report. Please close the defect.
