### ISSUE TITLE
Pactum spec makes multiple api calls

### ISSUE THREAD

**Issue by hemant-bs** [pactumjs/pactum#328]
**Describe the bug**
I have started my API automation using cucumber-pactum using this [template](https://github.com/pactumjs/pactum-cucumber-boilerplate). When I run my scenario my API is being hit multiple times, when I added a debugger to check which all calls are sending request I discovered these 3 commands are hitting request individually.

```js
await spec.withBearerToken(TOKEN); 
await spec.response().should.have.status(parseInt(code));
await spec.expectJsonLike(body);
```

**To Reproduce**

My cucumber feature file
```gherkin
    Given User makes a GET request to  <endpoint> API
    And I set basic authentication credentials
    When User receives a response
    Then User expects response should have a status <code>
    And User validates response for <test_data>
```
    
 My steps.js
    
```js
Before(() => {
  spec = pactum.spec();
  request.setDefaultTimeout(25000);
  setDefaultTimeout(25000);
});

Given(/^User makes a (.*) request to  (.*) API$/, { timeout: 600 * 1000 }, async function (method,endpoint) {

      await spec[method.toLowerCase()](endpoint);

});

Given(/^I set basic authentication credentials$/, async function () {
  await spec.withBearerToken(TOKEN); //first time call
});


When('User receives a response', async function () {
  const response = await spec.toss(); // second call
  globalResponse = response.body;
  console.log(globalResponse)
});

Then(/^User expects response should have a status ([0-9]+)$/, async function (code) {
  await spec.response().should.have.status(parseInt(code)); 
});

Then(/^User validates response for ([0-9a-zA-Z -_]+)$/, { timeout: 600 * 1000 }, async function (request) {
 
    await spec.expectJsonSchema(someBody); // third call
    spec = pactum.spec();
  }
  
```

**Expected behavior**

While chaining the requests it should call the API only once

**Software (please complete the following information):**

 - OS - MACOS 12.2.1 
 - Node js -  18.10.0
 - Test runner - cucumber-js

**Additional context**

**Comment by ASaiAnudeep** [comment]
Hello @hemant-bs,

`await` statement should be only used when we wanted to make a request and get the response.

Read More
- https://pactumjs.github.io/introduction/test-style.html
- https://pactumjs.github.io/api/requests/toss.html
