### ISSUE TITLE
Unable to use comma separated parameter value in DataunctionHandler

### ISSUE THREAD

**Issue by gourighode** [pactumjs/pactum#337]
### Discussed in https://github.com/pactumjs/pactum/discussions/336

<div type='discussions-op-text'>

<sup>Originally posted by **gourighode** April  3, 2024</sup>
We are using DataFunctionHandler concept to prepare request body with dynamic values for some keys.

In some of the scenarios value of specific key is comma separated 

Example of Sample handler

handler.addDataFuncHandler(’SamplePayLoad', (ctx) => {
  const source = ctx.args[0];
  console.log("*********************",source)
  const basePayload = {
    source: ctx.args[4],
  };
  return basePayload;
}); 

Value being passed for source while calling data function handler in actual test is A,B this combined value is needed for source however currently it is splitting it between 2 different parameters and hence value for source is appearing as only A

Can someone help in clarifying if is there any way to tackle this issue?</div>

**Comment by leelaprasadv** [comment]
@gourighode DataFunctions processor by default uses "," as a delimiter. To my knowledge, it's not that common to have "," in a key. 

With the above limitation, you will have to choose a different delimiter (ex: |, _, etc) in the source key while sending parameters to the Data Function and replace it in the Data function handler as a workaround.

```sh
const source = ctx.args[0].replace("|",",");
```

And data function invocation `$F{SamplePayload:A|B,....rest of params}`

**Comment by gourighode** [comment]
@leelaprasadv Even when we are passing array of values from DataFunctionHandler call it's splitting array values with "," delimiter. As long as I understand array with comma separated values will be common scenario to be passed from datafunction handler

e,g. 

const buildArray = [buildId1, buildId2];

.withBody(`$F{SamplePayload:${buildName},${buildArray},${projectId}}`)

**Comment by leelaprasadv** [comment]
Yes, as mentioned earlier - due to the limitation we have currently even arrays will not work. You will have to temporarily convert them into a delimited string (other than ",") before passing it to the function
