### ISSUE TITLE
Client certificate configuration when spec (post etc) is missing

### ISSUE THREAD

**Issue by erhard** [pactumjs/pactum#342]
when I run a spec.get  on a https url I get the following error

Error: unable to get local issuer certificate

So I created an agent  with

const https = require('https')
const agent = new https.Agent({ rejectUnauthorized: false });
and added it to the header before I made the spec.get(endpoint) call 
spec.withHeaders('httpsAgent', agent) 

This did not work in pactum

When I do the same with axios (same endpoint)  (adding the header with the agent to the axios call it works.

So I do not know what I did wrong and how to switch off ssl in pactum.
Where is the native call perhaps I can fix is myself, when it is an error.
An elgant solution would be a method spec.setSSL(boolean)

**Comment by leelaprasadv** [comment]
@erhard Here is the correct usage of pactum's withCore to add agent. https://pactumjs.github.io/api/requests/withCore.html

**Comment by erhard** [comment]
> @erhard Here is the correct usage of pactum's withCore to add agent. https://pactumjs.github.io/api/requests/withCore.html

Thank You very much for your efforts for pactum . It wroks as you suggested.
