### ISSUE TITLE
sequence of methods is important but not described or relevant

### ISSUE THREAD

**Issue by erhard** [pactumjs/pactum#344]
This works

 let response = await spec.get(endpoint).withCore({agent: agent}).withAuth(user,pwd);
           console.log(response);

This does not work (Auth error)

 let response = await spec.get(endpoint).withAuth(user,pwd).withCore({agent: agent});
           console.log(response);
           
           
  I think withCore overwrites withAuth

I would wish that the sequence of the method calls is not relevant.

**Comment by leelaprasadv** [comment]
Hi @erhard , Thanks for reporting the issue. Yes, it indeed is overriding the core options when the order is reversed. 
We will look into this soon.

**Comment by leelaprasadv** [comment]
Fixed in release in [v3.6.7](https://github.com/pactumjs/pactum/releases/tag/v3.6.7)
