### ISSUE TITLE
sleep after running a spec

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#349]
**Is your feature request related to a problem? Please describe.**
sleep after running a spec

**Describe the solution you'd like**
```js
await spec()
  .get('/path')
  .expectStatus(200)
  .sleep(1000);
```

**Describe alternatives you've considered**
```js
await spec()
  .get('/path')
  .expectStatus(200);

await sleep(1000);
```

**Additional context**
Can be used in spec handlers.

**Comment by baabouj** [comment]
@ASaiAnudeep I would love to work on this. Can I give it a try?
