### ISSUE TITLE
merge removeDefaultHeaders and removeDefaultHeader methods

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#365]
- merge removeDefaultHeaders and removeDefaultHeader methods
- update the docs

**Comment by raj356** [comment]
Hi @ASaiAnudeep, I am interested on the above, may I please try this out

**Comment by ASaiAnudeep** [comment]
@raj356 please go ahead.

**Comment by raj356** [comment]
@ASaiAnudeep thanks for giving me the opportunity to contribute to such an esteemed library. This task is completed now , please review the changes and provide feedback, I would be highly interested to hear back the same

**Comment by ASaiAnudeep** [comment]
Thank you for your contributions. I have merged both the PR's. I will release the changes by this week.

**Comment by raj356** [comment]
Thank you so much
