### ISSUE TITLE
Disable/Enable SSL certificate verification

### ISSUE THREAD

**Issue by ruslK** [pactumjs/pactum#370]
**Is your feature request related to a problem? Please describe.**
We are required to hit our endpoint which is HTTPS with SSL, and we are getting error: ` Error: unable to verify the first certificate` 

**Describe the solution you'd like**
Able to Disable and Enable SSL certificate verification

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ruslK** [comment]
I was able to disable with hardcode: `process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;`

**Comment by leelaprasadv** [comment]
@ruslK This has been answered [here](https://github.com/pactumjs/pactum/discussions/252#discussioncomment-4502648) 

Are these self signed certificates or  private network API call or behind a proxy ?

A working example that might be of help https://github.com/pactumjs/pactum/pull/293 

Note: You will have to ignore parts that doesn't relate to your case in the above example

**Comment by ruslK** [comment]
@leelaprasadv 
> Are these self signed certificates or private network API call or behind a proxy ?
- we don't use proxy. 

> Additionally, if you have the cert/key pair you can provide it the agent in withCore() and you should be able to make https requests. 
- we don't mock data, we do E2E, we are hitting actual endpoint in environment. 

We would be happy disable SSL with pactum, not with `process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;`

**Comment by ruslK** [comment]
@leelaprasadv 
Can I ask another question about Redirection? 
we have endpoint, which finish with 302 and should be redirected to another endpoint. 
When I execute that endpoint in postman, I see in logs that postman makes 5 another call with redirection. 
is possible to do with pactum?

**Comment by leelaprasadv** [comment]
@ruslK 
> we don't mock data, we do E2E, we are hitting actual endpoint in environment.

Yes, the example provides you with details on how to use an agent, the suggestion was to pick the block of code related to the agent from the example. 

```js
const https = require('https');

// If you have the cert/key pair
const key = fs.readFileSync("server.key")
const cert = fs.readFileSync("server.crt")

const agent = new https.Agent({
  cert: cert, // Optional - add if cert available 
  key: key, // Optional - add if key is available 
  rejectUnauthorized: false // Ignore  certificate errors
});

pactum.spec()
    .get('<https url>')
    .withCore({agent: agent })
    .expectStatus(200)

```


For follow Redirects, refer to the documention https://pactumjs.github.io/api/requests/withFollowRedirects.html#withfollowredirects

**Comment by ruslK** [comment]
@leelaprasadv 
about Redirect 
> For follow Redirects, refer to the documention https://pactumjs.github.io/api/requests/withFollowRedirects.html#withfollowredirects

what is deep of Redirect? one redirect or not? 
and how to config redirections? 
and how to see logs for redirections?

**Comment by leelaprasadv** [comment]
PactumJS relies on phin.js for http/https requests and it has a default follow redirect count of 20. Changes to support configuring redirect count can be expected in the next couple of releases. 

As for debug logs for redirects, `phin` under the hood uses `follow-redirects`, one option I see is to set an environment variable suggested in their readme doc
https://github.com/follow-redirects/follow-redirects/tree/main?tab=readme-ov-file#debug-logging

**Comment by ruslK** [comment]
@leelaprasadv 
thank for this tip:
> PactumJS relies on phin.js for http/https requests and it has a default follow redirect count of 20. Changes to support configuring redirect count in PactumJS can be expected in the next couple of releases.
> 
> As for debug logs for redirects, `phin` under the hood uses `follow-redirects`, one option I see is to set an environment variable suggested in their readme doc https://github.com/follow-redirects/follow-redirects/tree/main?tab=readme-ov-file#debug-logging

It is working, but I have issue with cookies, cookies are not passing for next redirected call. 
In postman there is config calls `Disable cookie jar` - if I disable in postman, i'm getting same problem with pactum. 
![image](https://github.com/user-attachments/assets/91a3d080-0aa3-4091-ac3b-fe21f867a8b0)

So it possible to Enable Cookies Jar with PactumJS?

**Comment by leelaprasadv** [comment]
> PactumJS relies on phin.js for http/https requests and it has a default follow redirect count of 20. Changes to support configuring redirect count in PactumJS can be expected in the next couple of releases. 
The above will be handled in #372 

Closing the issue as the original question is answered. Please follow up rest of the queries in existing discussions or start a new one if required.
