### ISSUE TITLE
Withmultipart_formdata is not accepting json payload

### ISSUE THREAD

**Issue by JyotiPMallick** [pactumjs/pactum#380]
**Describe the bug**

I am trying to make a post call with accept multipart form data, and one of its parameters (this one is mandatory) is only accepting JSON payload. But the spec handler is unable to identify the JSON data.

**To Reproduce**

My spec handler :

![image](https://github.com/user-attachments/assets/1d45f3d4-d077-4409-9ddc-952121f60b01)

My JSON payload which contains some synthetic data produced through function,

![image](https://github.com/user-attachments/assets/1670a967-9f75-43ef-88ee-168638685f64)

Now while running I am getting the below error,

![image](https://github.com/user-attachments/assets/46b253e6-427a-4e08-a0af-498e1a5da941)

Same thing from the browser

![image](https://github.com/user-attachments/assets/713e7e88-6235-4498-b447-cdd6aa7b9a09)

**Expected behavior**
It should add the details.

**Software (please complete the following information):**
 - OS: [Windows]
 - NodeJS Version [ 14]
 - Test Runner [e.g mocha]

Any clue what I am missing here ?

**Comment by ASaiAnudeep** [comment]
Hello @JyotiPMallick , is the `RegisterCompany` is a data template?

If so, we need to use `@DATA:TEMPLATE@`. For example:

```js
spec.withMultiPartFormData({ '@DATA:TEMPLATE@': 'RegisterCompany' })
```

**Comment by JyotiPMallick** [comment]
You mean something like `spec.withMultiPartFormData({ companyDto: {"@DATA:TEMPLATE@": "RegisterCompany" }});` ?

**Comment by JyotiPMallick** [comment]
addSpecHandler("Register a new company", ({ spec }) => {
  spec.post(paths.COMPANY_REGISTRATION);
  spec.withMultiPartFormData({ companyDto: {"@DATA:TEMPLATE@": "RegisterCompany" }});
  spec.expectStatus(200);
});

I am getting `TypeError: source.on is not a function` error.

**Comment by ASaiAnudeep** [comment]
Can you please share the stack trace of the error.

**Comment by JyotiPMallick** [comment]
```
  Registering a new company should return expected http status code 200 proper data in the response time.:
     TypeError: source.on is not a function
      at DelayedStream.create (node_modules\delayed-stream\lib\delayed_stream.js:33:10)
      at CombinedStream.append (node_modules\combined-stream\lib\combined_stream.js:45:37)
      at FormData.append (node_modules\form-data-lite\src\index.js:75:3)
      at setMultiPartFormData (node_modules\pactum\src\helpers\requestProcessor.js:134:34)
      at Object.process (node_modules\pactum\src\helpers\requestProcessor.js:22:5)
      at Tosser.toss (node_modules\pactum\src\models\Tosser.js:32:39)
      at Spec.toss (node_modules\pactum\src\models\Spec.js:540:19)
      at Spec.then (node_modules\pactum\src\models\Spec.js:544:10)
```

Here it is

**Comment by ASaiAnudeep** [comment]
I’m not sure whether this issue is related to Pactum, the underlying library, or a misunderstanding in the usage.
