### ISSUE TITLE
Typing and Doc do not match

### ISSUE THREAD

**Issue by Sufiane** [pactumjs/pactum#381]
**Describe the bug**
When adding multiple interactions to the same endpoint using the `onCall` property of the `response` object we are obliged to add a status to the upperscope of the request. It's firstly counterintuitive and secondly not stated in the documentation ([link](https://pactumjs.github.io/guides/mock-server.html#consecutive-calls))

<img width="460" alt="Screenshot 2024-10-15 at 11 34 27" src="https://github.com/user-attachments/assets/79653cf9-82ce-4cff-a212-8286d574936d">

**To Reproduce**
1. Add a mock with consecutive calls
2. stick to the documentation code
3. see the typescript compiler crying

**Expected behavior**
A different type for `onCall` behavior that do not need an upper scope `status` property.
Something that match the documentation

**Screenshots**
<img width="993" alt="Screenshot 2024-10-15 at 11 35 58" src="https://github.com/user-attachments/assets/878039f6-ce7d-47f0-bc3b-4a0a14013313">

**Software (please complete the following information):**
 - OS: [e.g. Windows] Mac os
 - NodeJS Version [e.g. 14] 20.15
 - Test Runner [e.g mocha] Jest 29.7

**Additional context**

**Comment by leelaprasadv** [comment]
@ASaiAnudeep aah, I totally forgot about this. I should have the changes stashed away in a branch. Let me check that and raise a PR soon.
