### ISSUE TITLE
Stores Append Object

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#391]
**Is your feature request related to a problem? Please describe.**

Append item to same path in the store

```js
await spec().post('/user').stores('USER', '.').stores('USER', 'req.body')
```

**Comment by Patrick1299** [comment]
![Screenshot_20241216-213920](https://github.com/user-attachments/assets/fc9bfbf4-501d-4343-b702-27ecaeb316b6)

**Comment by Patrick1299** [comment]
I want support about this ticket

**Comment by Patrick1299** [comment]
[rfc9698.pdf](https://github.com/user-attachments/files/18202335/rfc9698.pdf)

**Comment by Patrick1299** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Append item to same path in the store
> 
> ```js
> await spec().post('/user').stores('USER', '.').stores('USER', 'req.body')
> ```

I need help with everything to get done

**Comment by ASaiAnudeep** [comment]
I have closed this issue to fix the issue.

```js
await spec()
  .post('/user')
  .stores('USER', '.')
  .stores('USER', 'req.body', { merge: true })
```

**Comment by Patrick1299** [comment]
Please I'm new here I don't know the next option to take

**Comment by Patrick1299** [comment]
Subaccount_ BybitQsReMwcaFl2
UID_ 380839827
