### ISSUE TITLE
Support more HTTP methods

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#49]
### Background

PactumJS supports the following HTTP methods to perform a HTTP request.
- GET
- POST
- DELETE
- PATCH
- PUT
- HEAD

### Description

This issue focuses on expanding the supported list of HTTP methods to `TRACE` & `OPTIONS`.

```js
await pactum.spec()
  .trace('url')
  .expectStatus(200);
await pactum.spec()
  .options('url')
  .expectStatus(200);
```

Along with it, if a new HTTP method is available in the future then the users of this library should not be blocked by it. So the HTTP methods should be expandable. Introduce two new request making methods - `withMethod` & `withPath` that takes HTTP method & url as parameters.

```js
await pactum.spec()
  .withMethod('CONNECT')
  .withPath('url')
  .expectStatus(200);
```
 
### AC
1. Support `TRACE` & `OPTIONS` HTTP methods.
2. Support custom HTTP methods.
3. Add appropriate tests in `request.spec.js` under `test/component` folder.

**Comment by msharma-tw** [comment]
Hi Sai, I want to work on this issue. Can you assign this to me?
