### ISSUE TITLE
Retry on Expectation Failures

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#53]
### Background

PactumJS supports retry mechanism where an user can define when to retry (*strategy*), how many times to retry & the delay between retries.

```js
await pactum.spec()
  .get('/some/async/operation')
  .retry({
    count: 2,
    delay: 2000,
    strategy: ({res}) => { return res.statusCode === 200 }
  })
  .expectStatus(200);
``` 

### Description

Enhance the retry mechanism to retry when there are expectation failures.

#### Retry on expectations failure 

In the below test, if the endpoint returns a status code other than 202, PactumJS should retry the API request.

```js
await pactum.spec()
  .get('/api/endpoint')
  .expectStatus(202)
  .retry();
``` 
The retry logic should apply for other expectation failures as well.

#### Support multiple options in retry() method 

Retry with default options

```js
retry() 
```

Retry with a custom retry count

```js
retry(3); 
```

Retry with a custom retry count & custom delay

```js
retry(3, 5000); 
```

### AC

1. PactumJS should retry on expectation failures.
2. Add tests.

**Comment by ankurjain00** [comment]
Hello @ASaiAnudeep could you assign this issue to me
