### ISSUE TITLE
Support sending and asserting cookies

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#57]
### Background

An HTTP cookie (web cookie, browser cookie) is a small piece of data that a server sends to the user's web browser. The browser may store it and send it back with later requests to the same server.

Learn more about cookies [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies).

### Description

This issue focuses on sending cookies & asserting cookies in a friendly way with PactumJS.

##### Key-Value

```js
withCookies('name', 'snow')
```

##### Object

```js
withCookies({
  name: 'snow',
  'HttpOnly': null
})
```

##### Raw

```js
withCookies('name=snow;HttpOnly')
```

Support multiple cookies.

```js
await pactum.spec()
  .get('url')
  .withCookies('key1', 'value1')
  .withCookies('key2', 'value2')
```

#### Asserting Cookies

To support rich assertions, use json-like or json-match internally. I prefer json-match.

```js
await pactum.spec()
  .get('url')
  .expectCookies('key1', 'value1');
``` 

##### Key-Value

```js
expectCookies('name', 'snow')
```

##### Object

```js
expectCookies({
  name: 'snow',
  'HttpOnly': null
})

expectStrictCookies({
  name: 'snow',
  'HttpOnly': null
})
```

##### Raw

```js
expectCookies('name=snow;HttpOnly')
```

#### Note

Use lightweight cookie parsers like [lightcookie](https://www.npmjs.com/package/lightcookie) or [simple-cookie](https://www.npmjs.com/package/simple-cookie).

### AC

1. PactumJS should support sending & asserting cookies.
2. Add `withCookies`, `expectCookies` & `expectStrictCookies`.
3. Add tests

**Comment by msharma-tw** [comment]
Hi Anudeep, Can you assign me this issue.
