### ISSUE TITLE
Support adding multiple interactions from Interaction Handlers

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum#59]
### Background

Interaction handlers are a way to reuse interactions across your test cases. With the current setup, we can only return one interaction in the callback function. 

```js
const { addInteractionHandler } = require('pactum').handler;

addInteractionHandler('get users', () => {
  return {
    request: {
      method: 'GET',
      path: '/api/users'
    },
    response: {
      status: 200
    }
  }
}); 
```

### Description

Enhance the `addInteractionHandler` function to return multiple interactions.

```js
const { addInteractionHandler } = require('pactum').handler;

addInteractionHandler('get users with id 1 & 2', () => {
  return [
  {
    request: {
      method: 'GET',
      path: '/api/users/1'
    },
    response: {
      status: 200,
      body: { "id": 1 }
    }
  },
  {
    request: {
      method: 'GET',
      path: '/api/users/2'
    },
    response: {
      status: 200,
      body: { "id": 2 }
    }
  }];
}); 
```

#### Potential Changes

- [mock.js](https://github.com/pactumjs/pactum/blob/master/src/exports/mock.js#L31-L53)
- [handler.runner.js](https://github.com/pactumjs/pactum/blob/master/src/helpers/handler.runner.js)

### AC

1. `addInteractionHandler` function should support multiple interactions
2. Add tests

**Comment by sudhakotni-git** [comment]
I would like to work on this
