### ISSUE TITLE
Option to disable console logs.

### ISSUE THREAD

**Issue by bartekbujak** [pactumjs/pactum#68]
Hi would be fine, to add option to disable logs during tests:

```
class Server 
          log.info(Mock server is listening on port ${config.mock.port}); //start method
          log.info(Mock server server stopped on port ${config.mock.port}); //stop method
```
current behaviour:
``` 
PASS  test/functional/example.spec.ts
  ● Console

    console.info
      Mock server is listening on port 9339

      at node_modules/pactum/src/exports/logger.js:69:37
          at Array.forEach (<anonymous>)

    console.info
      Mock server stopped on port 9339

      at node_modules/pactum/src/exports/logger.js:69:37
          at Array.forEach (<anonymous>)
```

Solutions:
1. Change log error level from info to debug, then it could be omit by `process.env.PACTUM_LOG_LEVEL`
2. Add another parameter to `mock`
```
    await pactum.mock.start(9339, {loggerEnabled: false});
```

**Comment by ASaiAnudeep** [comment]
The default log-level in pactum is **INFO**. We can update it from settings.

Include this at the start of your test execution.

```js
const { settings } = require('pactum');

settings.setLogLevel('ERROR');
```

More details [here](https://pactumjs.github.io/#/api-settings).

I understand we might need additional log levels like - **SILENT** & **VERBOSE**

**Comment by bartekbujak** [comment]
> The default log-level in pactum is **INFO**. We can update it from settings.
> 
> Include this at the start of your test execution.
> 
> ```js
> const { settings } = require('pactum');
> 
> settings.setLogLevel('ERROR');
> ```
> 
> More details [here](https://pactumjs.github.io/#/api-settings).
> 
> I understand we might need additional log levels like - **SILENT** & **VERBOSE**

I have not seen that option. Thanks for reply.
