### ISSUE TITLE
Feature Request: External JSON schema

### ISSUE THREAD

**Issue by emfomy** [pactumjs/pactum#74]
**Is your feature request related to a problem? Please describe.**
I want to use external JSON schema provided in [@exodus/schemasafe](https://www.npmjs.com/package/@exodus/schemasafe#custom-formats)

**Describe the solution you'd like**
Please add an optional argument for external schemas to `expectJsonSchema` and `jsonSchema` methods.

**Describe alternatives you've considered**
Or maybe add a global setting for external schemas.

**Comment by ASaiAnudeep** [comment]
PactumJS now supports passing custom options to json schema validations.

```js
await pactum.spec()
  .get('api/get')
  .expectJsonSchema(
    {
      type: 'object',
      properties: {
        method: {
          type: 'string',
          format: 'only-get'
        }
      }
    },
    {
      formats: {
        'only-get': /^GET$/
      }
    }
  );
```
