### ISSUE TITLE
require error in documentation

### ISSUE THREAD

**Issue by mikeysan** [pactumjs/pactum#80]
**Describe the bug**
On your documentation website there is a reference to install cucumber  using:
```npm install @cucumber/cucumber -g```
However, when you require the module later, you use `require('cucumber')`, which generates and error.

**To Reproduce**
Check the documentation site, and I just noticed it is the same in the readme here (on github).

**Expected behavior**
The line should read ```const { Given, When, Then, Before } = require('@cucumber/cucumber');```

**Screenshots**
![image](https://user-images.githubusercontent.com/13338176/130233536-6f8e663d-41a7-4f9e-a881-1ff1e996b32b.png)

**Software (please complete the following information):**
N/A

**Additional context**

**Comment by ASaiAnudeep** [comment]
Thanks for reporting. Fixed it. 
I'm watching EddieCon 💯
