### ISSUE TITLE
How to upload binary file?

### ISSUE THREAD

**Issue by emfomy** [pactumjs/pactum#87]
How to upload a binary file (not using form-data)?

**Comment by ASaiAnudeep** [comment]
Files can be uploaded through `withFile` method. But it internally uses `form-data`. Not sure on how to upload a binary file without using form-data. 

Do you have an example code that works with any other popular libraries like [phin](https://www.npmjs.com/package/phin) or [request](https://www.npmjs.com/package/request)? Or even a Postman example would help!

**Comment by emfomy** [comment]
In Postman's body tab, there is an option `binary`, which allows me to upload a single file.

I'm not sure if the implementation is different from the one using `form-data`.

However, in my scenario, I found that it is possible to upload the file using
```javascript
fileType = 'image/jpeg'; // or any other content type
spec.withBody(fs.readFileSync(filePath));
spec.withHeaders('Content-Type', fileType);
```

Is this the correct way to use this library?

**Comment by ASaiAnudeep** [comment]
That’s a great idea 👍. I will use this issue to add it as an enhancement.
