### ISSUE TITLE
Cannot get interaction with the specified ID

### ISSUE THREAD

**Issue by rebortyang** [pactumjs/pactum#90]
**Describe the bug**
mockserver.js
`mock.addInteraction({
        id:'first',
        request:{...},
        response:{...}
`
getInteraction.test.js
`
test('should return "Jon" info',async()=>{
        await pactum.spec()
                .get('http://localhost:3000/ms/api/users/{userId}')
                .withPathParams({"userId":"1"})
                .expectStatus(200)
                .expectJsonLike({
                        id: 1,
                        name:'Jon'
                });

        expect(mock.getInteraction('first')).not.toBe(null);

});
`
results:

    Interaction Not Found - first

      at msg.forEach.m (node_modules/pactum/src/adapters/logger.js:21:24)
          at Array.forEach (<anonymous>)
      at Object.warn (node_modules/pactum/src/adapters/logger.js:21:7)
      at Logger.warn (node_modules/pactum/src/plugins/logger.js:78:20)
      at Server.getInteraction (node_modules/pactum/src/models/server.js:77:11)
      at ids.forEach.id (node_modules/pactum/src/exports/mock.js:72:54)
          at Array.forEach (<anonymous>)

FAIL __tests__/mockServer/interactionWithPathParams.test.js
  × should return "Jon" info (50 ms)

  ● should return "Jon" info

    TypeError: Cannot read property 'callCount' of null

      15 |              });
      16 |
    > 17 |      expect(mock.getInteraction('first')).not.toBe(null);
         |                  ^
      18 |
      19 | });
      20 |

      at interactions.forEach.interaction (node_modules/pactum/src/exports/mock.js:74:43)
          at Array.forEach (<anonymous>)

**How do I get interaction with the given ID?**

**Comment by leelaprasadv** [comment]
Your mock interaction doesn't seem to be added properly. So its unable to find the interaction.

There are couple of ways to solve this:
1. Using `handlers` and `useInteration` methods for more control on mocks. details here:  https://pactumjs.github.io/#/component-testing?id=interaction-handlers
2. require the mock server.js

mockserver.js
```js
const {mock} = require('pactum');

mock.addInteraction({
  id: 'first',
  request: {
      method: 'GET',
      path: '/api/users/{userId}',
      pathParams: {
        userId: '1'
      }
  },
  response: {
      status: 200,
      body: {
          id: 1,
          name: 'Jon'
      }
  }
});
```

getInteraction.test.js
```js
const { mock, spec } = require('pactum');
const expect = require('expect')

require('./mockserver');

beforeAll(async () => {
    await mock.start(3000);
});

afterAll(async () => {
    await mock.stop();
});


test('should return "Jon" info', async () => {
    await spec()
        .get('http://localhost:3000/api/users/{userId}')
        .withPathParams({
            "userId": "1"
        })
        .expectStatus(200)
        .expectJsonLike({
            id: 1,
            name: 'Jon'
        });
    expect(mock.getInteraction('first')).not.toBe(null);
})
```

**Comment by ASaiAnudeep** [comment]
Thanks for reporting @rebortyang.

The solution provided by @leelaprasadv works. Anyway I will be tagging this issue as a bug, since the library should not throw an error when passing an invalid id.

**Comment by rebortyang** [comment]
@ASaiAnudeep @leelaprasadv  thank you.
