### ISSUE TITLE
Requests signed with certificates(PEM/Key)

### ISSUE THREAD

**Issue by fejsrodrigues** [pactumjs/pactum#94]
**Is your feature request related to a problem? Please describe.**
i would like to send some request signed with certificates(PEM/KEY). but i cant passed a the certificate.

**Describe the solution you'd like**
i would like to passe a certificate via file or string, and it send my request.

**Comment by ASaiAnudeep** [comment]
This is an interesting use case. I haven't came across into such scenario.

To further understand the requirement, do you have an example to perform such request with any other popular libraries like [http](https://nodejs.org/api/http.html#httprequestoptions-callback), [request](https://www.npmjs.com/package/request) or [phin](https://www.npmjs.com/package/phin).

If you an example code with **phin**, that would really help us to tackle this requirement.

**Comment by fejsrodrigues** [comment]
i found this example using [**Request**](https://www.npmjs.com/package/request#tlsssl-protocol)


```
const fs = require('fs')
    , path = require('path')
    , certFile = path.resolve(__dirname, 'ssl/client.crt')
    , keyFile = path.resolve(__dirname, 'ssl/client.key')
    , caFile = path.resolve(__dirname, 'ssl/ca.cert.pem')
    , request = require('request');
 
const options = {
    url: 'https://api.some-server.com/',
    cert: fs.readFileSync(certFile),
    key: fs.readFileSync(keyFile),
    passphrase: 'password',
    ca: fs.readFileSync(caFile)
};
 
request.get(options);
```

i didnt find example with **Phin**

Thanks!

**Comment by ASaiAnudeep** [comment]
You need to create a new agent with all the certification information and them pass the information to `withCore` method.

```js
const http = require('http');
const agent = new http.Agent({ 
  cert: '',
  key: ''
});


const pactum = require('pactum');

await pactum.spec()
  .get('<url>')
  .withCore({ agent });
```

I hope this would work.

**Comment by fejsrodrigues** [comment]
``I made a small change and its working

```javascript

const https = require('https');
let pem = path.resolve(__dirname, 'your-path-pem')
let key = path.resolve(__dirname, 'your-path-key')

const agent = new https.Agent({ 
            cert: fs.readFileSync(pem),
            key: fs.readFileSync(key),
            passphrase: ""            
 });

await pactum.spec()
     .post('your-uri')
     .withBody(body)
     .withCore({ agent })

```

**Comment by crystalfp** [comment]
As I wrote in https://github.com/pactumjs/pactum/discussions/252#discussioncomment-4501041,
also with the suggestion above, Pactum complains that it is `UNABLE_TO_VERIFY_LEAF_SIGNATURE`. Instead accessing my server over http2 succeeded.
